title: My Portfolio
description: Мое портфолио на GitHub Pages
theme: jekyll-theme-minimal
url: "https://matejkoas.github.io" # Укажи свой URL, если есть

# Настройки коллекций
collections:
  cases:
    output: true  # Включает обработку файлов в коллекции и их вывод на сайт

# Параметры шаблонов
# Указываем, какие шаблоны использовать для разных страниц
# и коллекций. Например, для страниц в корне сайта и для кейсов.
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "cases/*"
      type: "cases"
    values:
      layout: "case"  # Указываем шаблон для кейсов

# Параметры для генерации страницы
markdown: kramdown  # Использование kramdown для рендеринга Markdown

# Персонализированные переменные
author: "Matejkoas"
email: "matejkoas@gmail.com"

# Подсветка
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css: style
    guess_lang: false
syntax_highlighter_opts:
    default_lang: python
    guess_lang: false